연산


In [1]:
import pandas as pd
import numpy as np
st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90,'영어':80})

print(st1,'\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    80
dtype: int64


In [5]:
# 두 학생의 과목별 점수로 사칙연산 수행
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)
df = pd.concat([add,sub,mul,div],axis=1)
df

0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [7]:
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

result = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [8]:
li = list('abcd')
li

['a', 'b', 'c', 'd']

In [9]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

df2.loc[1,'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [10]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
# 연산메소드(add(), sub(), mul(), div())와 fill_value()
# Q. df2의 NaN 값을 0으로 대체 후 사칙연산을 수행하세요.

In [12]:
add_data = df1.add(df2,fill_value=0)
sub_data = df1.sub(df2, fill_value=0)
mul_data = df1.mul(df2, fill_value=0)
div_data = df1.div(df2, fill_value=0)
print(add_data,'\n')
print(sub_data,'\n')
print(mul_data,'\n')
print(div_data,'\n')

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0 

      a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0   5.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0 

      a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0   0.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0 

     a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8       inf  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0 



In [14]:
print(df1,'\n')
print(1/df1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909


In [15]:
# 계산인자를 뒤집어 계산
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [17]:
print(df1)
df1.rsub(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [19]:
print(df1)
df1.radd(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [20]:
print(df1)
df1.rmul(10)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b      c      d
0   0.0  10.0   20.0   30.0
1  40.0  50.0   60.0   70.0
2  80.0  90.0  100.0  110.0

In [21]:
# reindex할 때도 fill_value 지정
df1.reindex(columns=df2.columns,fill_value=0)


a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [22]:
# 배열의 연산
arr = np.arange(12.).reshape(3,4)
print(arr,'\n')
print(arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.]


In [23]:
# broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [24]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [25]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [26]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [27]:
series2 = pd.Series(range(3),index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [29]:
print(frame,'\n')
frame + series2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0 



b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [30]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [32]:
print(frame,'\n')
frame.sub(series3,axis='index')

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0 



b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [33]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [34]:
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [36]:
a = np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

In [40]:
# 함수 적용과 매핑
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -2.155876  0.588667 -0.986228
Ohio   -1.003634  0.103495 -0.443402
Texas   0.709309  0.331136  0.775696
Oregon -0.998970  0.415681  1.601540

In [41]:
np.abs(frame)

b         d         e
Utah    2.155876  0.588667  0.986228
Ohio    1.003634  0.103495  0.443402
Texas   0.709309  0.331136  0.775696
Oregon  0.998970  0.415681  1.601540

커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map함수 : DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용
- apply함수 : 커스텀 함수를 사용하기 위해 DataFrame에서 복수 개의 컬럼이 필요하다면, apply함수를 사용
- applymap함수 : DataFrame클래스의 함수이긴 하나, 위의 apply함수처럼 각 row(axis=1)나 각 column(axis=0)별로 
작동하는 함수가 아니라, 각 요소(element)별로 작동  
마치 선형대수에서 벡터에 스칼라를 연산하면, 벡터의 요소 하나하나에 해당 연산을 해주는 것처럼(elementwise) 
적용하는 DataFrame의 각 요소마다 커스텀 함수(반드시 Single vaule를 반환하는)를 수행한다고 보면 된다. 
applymap에 인자로 전달하는 커스텀함수가 Single value로부터 Single value를 반환한다는 점이 중요하다

In [42]:
# series의 최대값과 최소값의 차이를 계산
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.865185
d    0.485172
e    2.587768
dtype: float64

In [43]:
# 각 로우에 대해서 한 번씩 수행
frame.apply(f,axis='columns')

Utah      2.744543
Ohio      1.107129
Texas     0.444560
Oregon    2.600510
dtype: float64

In [44]:
# 여러값을 가진 Series 반환
print(frame,'\n')
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])
frame.apply(f)

               b         d         e
Utah   -2.155876  0.588667 -0.986228
Ohio   -1.003634  0.103495 -0.443402
Texas   0.709309  0.331136  0.775696
Oregon -0.998970  0.415681  1.601540 



b         d         e
min -2.155876  0.103495 -0.986228
max  0.709309  0.588667  1.601540

In [45]:
# 실수값을 문자열 포맷으로 변환
format = lambda x: '%.2f' %x
frame.applymap(format)

b     d      e
Utah    -2.16  0.59  -0.99
Ohio    -1.00  0.10  -0.44
Texas    0.71  0.33   0.78
Oregon  -1.00  0.42   1.60

In [46]:
# map함수는 series에만 적용
frame['e'].map(format)

Utah      -0.99
Ohio      -0.44
Texas      0.78
Oregon     1.60
Name: e, dtype: object


Q. 데이터를 아래와 같이 수정한 후 연도별 판매금액 증감여부에 따라서 고객을 구매금액의 증가, 감소를 기준으로 1,0으로 구분하는 파생변수를 생성하세요.

[데이터 수정 사항]

상품별 가격대 결정 : 1 ~ 5번 상품 평균가격을 1000 ~ 50000원으로 산정(1000, 5000, 10000, 25000, 50000 )  
판매 수량 성장율: 저가(1000, 5000) 20%, 중가(10000,25000) -10%, 고가(50000) 5% 성장 
상품 비중(판매금액 기준) : 저가 50%, 중가 30%, 고가 20%  
고객 비중도 상품 비중과 동일  
판매금액 변수 생성 (a_19, a_20) : 판매수량 * 평균가격

In [47]:
import numpy as np
import pandas as pd

id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,81,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)
pdt_19 = np.random.randint(1, 6,size=1000)
p_19 = pd.Series(pdt_19)
pdt_20 = np.random.randint(1, 6,size=1000)
p_20 = pd.Series(pdt_20)
price_avg_19 = np.random.rand(1000)
pr19 = price_avg_19*10000
pa_19 = pd.Series(pr19)
price_avg_20 = np.random.rand(1000)
pr20 = price_avg_20*10000
pa_20 = pd.Series(pr20)
qty_19 = np.random.randint(1,101, 1000)
q_19 = pd.Series(qty_19)
qty_20 = np.random.randint(1,101, 1000)
q_20 = pd.Series(qty_20)
time_19 = np.random.randint(1, 24, 1000)
t_19 = pd.Series(time_19)
time_20 = np.random.randint(1, 24, 1000)
t_20 = pd.Series(time_20)
df = pd.concat([i1, g1,a1,r1,p_19,p_20,pa_19,pa_20,q_19,q_20,t_19,t_20],axis=1)
df.rename(columns={0:'id',1:'gender',2:'age',3:'region',4:'pdt_19',5:'pdt_20',6:'pa_19',7:'pa_20',\
                  8:'q_19',9:'q_20',10:'t_19',11:'t_20'},inplace=True)
df['pa_19'] = round(df['pa_19'],2)
df['pa_20'] = round(df['pa_20'],2)
df.iloc[0,1] = np.nan
print(type(pa_19))
df.head()

<class 'pandas.core.series.Series'>


id  gender  age  region  pdt_19  pdt_20    pa_19    pa_20  q_19  q_20  \
0   1     NaN    5       6       2       3  7514.94  7190.14    68    14   
1   2     0.0   35       6       3       2  5775.01  3210.76    67    97   
2   3     0.0   58       4       5       1   793.22  5219.88    96    31   
3   4     0.0   34      10       3       5  5860.92  7517.87    50    44   
4   5     0.0   22       1       3       1  6050.41  4050.06    84    91   

   t_19  t_20  
0     1     7  
1    12    11  
2    23    17  
3    12    18  
4    13     3